DROP TABLE IF EXISTS `dbc_spellcasttimes`; 
CREATE TABLE `dbc_spellcasttimes` ( `ID` INT NOT NULL DEFAULT '0', `Base` INT NOT NULL DEFAULT '0', `PerLevel` INT NOT NULL DEFAULT '0', `Minimum` INT NOT NULL DEFAULT '0', PRIMARY KEY (`ID`)) ENGINE=MyISAM DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS `dbc_spellduration`; 
CREATE TABLE `dbc_spellduration` ( `ID` INT NOT NULL DEFAULT '0', `Duration` INT NOT NULL DEFAULT '0', `DurationPerLevel` INT NOT NULL DEFAULT '0', `MaxDuration` INT NOT NULL DEFAULT '0', PRIMARY KEY (`ID`)) ENGINE=MyISAM DEFAULT CHARSET=utf8; 
